### ISSUE TITLE
Mismatch for project name in xmake.lua

### ISSUE THREAD

**Issue by FlayaN** [Starfield-Reverse-Engineering/commonlibsf-template-xmake#2]
https://github.com/Starfield-Reverse-Engineering/commonlibsf-template-xmake/blob/ec9811b3281c4f3e804d094ce9c0107ee7c3ef8c/xmake.lua#L8

https://github.com/Starfield-Reverse-Engineering/commonlibsf-template-xmake/blob/ec9811b3281c4f3e804d094ce9c0107ee7c3ef8c/xmake.lua#L23

https://github.com/Starfield-Reverse-Engineering/commonlibsf-template-xmake/blob/ec9811b3281c4f3e804d094ce9c0107ee7c3ef8c/xmake.lua#L29

Shouldn't these match? Maybe create a variable instead to make it easier to change the plugin name as well?

**Comment by Qudix** [comment]
Fixed that. 

They can all be different if the user so chooses. The project name is the *overall* project name. For example, you can have multiple different targets/plugins built under one project umbrella. This project name is refleted under the resulting .dlls details tab.
